"""
MANAGER UI - Form Fields Section
This shows the updated form fields in the assign_task_page.dart
"""

// STATE VARIABLES (Add to _AssignTaskPageState class)
String? _selectedEquipmentType;
String _equipmentTag = '';
String? _selectedArea;
String? _autoGeneratedInspectionId;  // Display only
String? _autoGeneratedReportNumber;   // Display only
String _tagValidationError = '';

// VALIDATION FUNCTION
String? _validateEquipmentTag(String? value) {
  if (value == null || value.isEmpty) {
    return 'Equipment tag is required';
  }
  
  if (_selectedEquipmentType == null) {
    return 'Please select equipment type first';
  }
  
  final prefix = EquipmentData.getTagPrefix(_selectedEquipmentType!);
  final valueUpper = value.toUpperCase();
  
  if (!valueUpper.startsWith(prefix)) {
    return 'Tag must start with $prefix';
  }
  
  final numberPart = valueUpper.substring(prefix.length);
  if (!RegExp(r'^\d{3}$').hasMatch(numberPart)) {
    return 'Tag must be ${prefix}XXX where X is a digit (e.g., ${prefix}001)';
  }
  
  return null;
}

// UPDATED FORM SECTION
Widget _buildFormSection() {
  return Container(
    padding: const EdgeInsets.all(32),
    decoration: BoxDecoration(
      color: Colors.white,
      borderRadius: BorderRadius.circular(16),
    ),
    child: Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // HEADER
        Text(
          'Inspection Task Assignment',
          style: GoogleFonts.inter(
            fontSize: 20,
            fontWeight: FontWeight.w700,
            color: AppTheme.textPrimary,
          ),
        ),
        const SizedBox(height: 8),
        Text(
          'Fill in the details below to assign a new inspection task',
          style: GoogleFonts.inter(
            fontSize: 14,
            color: AppTheme.textSecondary,
          ),
        ),
        const SizedBox(height: 32),
        
        // AUTO-GENERATED IDs (READ-ONLY DISPLAY)
        if (_autoGeneratedInspectionId != null) ...[
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: AppTheme.primaryRed.withOpacity(0.05),
              borderRadius: BorderRadius.circular(12),
              border: Border.all(
                color: AppTheme.primaryRed.withOpacity(0.2),
              ),
            ),
            child: Row(
              children: [
                Icon(Icons.info_outline, color: AppTheme.primaryRed, size: 20),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Auto-Generated IDs',
                        style: GoogleFonts.inter(
                          fontSize: 12,
                          fontWeight: FontWeight.w600,
                          color: AppTheme.textSecondary,
                        ),
                      ),
                      const SizedBox(height: 4),
                      Row(
                        children: [
                          Text(
                            'Inspection ID: ',
                            style: GoogleFonts.inter(
                              fontSize: 14,
                              color: AppTheme.textSecondary,
                            ),
                          ),
                          Text(
                            _autoGeneratedInspectionId!,
                            style: GoogleFonts.inter(
                              fontSize: 14,
                              fontWeight: FontWeight.w700,
                              color: AppTheme.primaryRed,
                            ),
                          ),
                          const SizedBox(width: 24),
                          Text(
                            'Report Number: ',
                            style: GoogleFonts.inter(
                              fontSize: 14,
                              color: AppTheme.textSecondary,
                            ),
                          ),
                          Text(
                            _autoGeneratedReportNumber!,
                            style: GoogleFonts.inter(
                              fontSize: 14,
                              fontWeight: FontWeight.w700,
                              color: AppTheme.primaryRed,
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 24),
        ],
        
        // TASK TITLE
        _buildTextField(
          label: 'Task Title',
          hint: 'Enter inspection task title',
          controller: _titleController,
          required: true,
        ),
        const SizedBox(height: 24),
        
        // EQUIPMENT TYPE DROPDOWN
        Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Text(
                  'Equipment Type',
                  style: GoogleFonts.inter(
                    fontSize: 14,
                    fontWeight: FontWeight.w600,
                    color: AppTheme.textPrimary,
                  ),
                ),
                const SizedBox(width: 4),
                Text(
                  '*',
                  style: GoogleFonts.inter(
                    fontSize: 14,
                    fontWeight: FontWeight.w600,
                    color: AppTheme.primaryRed,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 8),
            Container(
              decoration: BoxDecoration(
                color: AppTheme.backgroundColor,
                borderRadius: BorderRadius.circular(12),
                border: Border.all(color: Colors.grey.shade300),
              ),
              child: DropdownButtonFormField<String>(
                value: _selectedEquipmentType,
                decoration: InputDecoration(
                  contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                  border: InputBorder.none,
                  hintText: 'Select equipment type',
                  hintStyle: GoogleFonts.inter(color: Colors.grey),
                ),
                items: EquipmentData.types.map((type) {
                  return DropdownMenuItem(
                    value: type,
                    child: Text(
                      type,
                      style: GoogleFonts.inter(fontSize: 14),
                    ),
                  );
                }).toList(),
                onChanged: (value) {
                  setState(() {
                    _selectedEquipmentType = value;
                    _equipmentTag = '';  // Reset tag when type changes
                    _tagValidationError = '';
                  });
                },
              ),
            ),
          ],
        ),
        const SizedBox(height: 24),
        
        // EQUIPMENT TAG NUMBER
        Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Text(
                  'Equipment Tag Number',
                  style: GoogleFonts.inter(
                    fontSize: 14,
                    fontWeight: FontWeight.w600,
                    color: AppTheme.textPrimary,
                  ),
                ),
                const SizedBox(width: 4),
                Text(
                  '*',
                  style: GoogleFonts.inter(
                    fontSize: 14,
                    fontWeight: FontWeight.w600,
                    color: AppTheme.primaryRed,
                  ),
                ),
              ],
            ),
            if (_selectedEquipmentType != null) ...[
              const SizedBox(height: 4),
              Text(
                'Format: ${EquipmentData.getTagFormat(_selectedEquipmentType!)}',
                style: GoogleFonts.inter(
                  fontSize: 12,
                  color: AppTheme.textSecondary,
                  fontStyle: FontStyle.italic,
                ),
              ),
            ],
            const SizedBox(height: 8),
            TextField(
              enabled: _selectedEquipmentType != null,
              onChanged: (value) {
                setState(() {
                  _equipmentTag = value.toUpperCase();
                  _tagValidationError = _validateEquipmentTag(value) ?? '';
                });
              },
              decoration: InputDecoration(
                filled: true,
                fillColor: _selectedEquipmentType == null 
                    ? Colors.grey.shade100 
                    : AppTheme.backgroundColor,
                contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                  borderSide: BorderSide(color: Colors.grey.shade300),
                ),
                enabledBorder: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                  borderSide: BorderSide(
                    color: _tagValidationError.isEmpty 
                        ? Colors.grey.shade300 
                        : AppTheme.primaryRed,
                  ),
                ),
                hintText: _selectedEquipmentType == null
                    ? 'Select equipment type first'
                    : 'Enter tag number (e.g., ${EquipmentData.getTagPrefix(_selectedEquipmentType!)}001)',
                hintStyle: GoogleFonts.inter(color: Colors.grey),
                errorText: _tagValidationError.isEmpty ? null : _tagValidationError,
              ),
              style: GoogleFonts.inter(
                fontSize: 14,
                fontWeight: FontWeight.w600,
                letterSpacing: 1.2,
              ),
            ),
          ],
        ),
        const SizedBox(height: 24),
        
        // AREA DROPDOWN
        Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Text(
                  'Area',
                  style: GoogleFonts.inter(
                    fontSize: 14,
                    fontWeight: FontWeight.w600,
                    color: AppTheme.textPrimary,
                  ),
                ),
                const SizedBox(width: 4),
                Text(
                  '*',
                  style: GoogleFonts.inter(
                    fontSize: 14,
                    fontWeight: FontWeight.w600,
                    color: AppTheme.primaryRed,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 8),
            Container(
              decoration: BoxDecoration(
                color: AppTheme.backgroundColor,
                borderRadius: BorderRadius.circular(12),
                border: Border.all(color: Colors.grey.shade300),
              ),
              child: DropdownButtonFormField<String>(
                value: _selectedArea,
                decoration: InputDecoration(
                  contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                  border: InputBorder.none,
                  hintText: 'Select area',
                  hintStyle: GoogleFonts.inter(color: Colors.grey),
                ),
                items: EquipmentData.areas.map((area) {
                  return DropdownMenuItem(
                    value: area,
                    child: Text(
                      area,
                      style: GoogleFonts.inter(fontSize: 14),
                    ),
                  );
                }).toList(),
                onChanged: (value) {
                  setState(() {
                    _selectedArea = value;
                  });
                },
              ),
            ),
          ],
        ),
        const SizedBox(height: 24),
        
        // REQUIRED SECTIONS (EXISTING CHECKBOXES - KEEP AS IS)
        _buildSectionCheckboxes(),
        
        const SizedBox(height: 24),
        
        // INSPECTOR DROPDOWN (EXISTING - KEEP AS IS)
        _buildInspectorDropdown(),
        
        const SizedBox(height: 24),
        
        // DUE DATE (EXISTING - KEEP AS IS)
        _buildDatePicker(),
        
        const SizedBox(height: 32),
        
        // SUBMIT BUTTON
        SizedBox(
          width: double.infinity,
          child: ElevatedButton(
            onPressed: _canSubmit() ? _submitTask : null,
            style: ElevatedButton.styleFrom(
              backgroundColor: AppTheme.managerPrimary,
              padding: const EdgeInsets.symmetric(vertical: 16),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(12),
              ),
            ),
            child: Text(
              'Assign Task',
              style: GoogleFonts.inter(
                fontSize: 16,
                fontWeight: FontWeight.w600,
                color: Colors.white,
              ),
            ),
          ),
        ),
      ],
    ),
  );
}

// VALIDATION CHECK
bool _canSubmit() {
  return _titleController.text.isNotEmpty &&
         _selectedEquipmentType != null &&
         _equipmentTag.isNotEmpty &&
         _validateEquipmentTag(_equipmentTag) == null &&
         _selectedArea != null &&
         _selectedInspectorId != null &&
         _selectedDate != null &&
         (_requireExternal || _requireWeld || _requireInternal || _requireThickness);
}
